---
- hosts: all
  sudo: true
  tasks:
    - apt: update_cache=yes
    - name: install packages
      apt: name={{ item }} state=present
      with_items:
        - nginx-extras
        - uwsgi-core
        - uwsgi-plugin-python3
        - python3-pip
        - postgresql
        - libpq-dev
        - python3-dev
        - python-virtualenv
    - command: virtualenv --python=python3 /opt/venv
    - command: /opt/venv/bin/pip install --upgrade pip
    - command: /opt/venv/bin/pip install -r /opt/code/requirements.txt
    - file: path=/var/log/uwsgi state=directory
    - file: path=/etc/uwsgi/apps-enabled state=directory
    - copy: src=deploy/uwsgi.conf dest=/etc/init/uwsgi.conf
    - copy: src=deploy/uwsgi.ini dest=/etc/uwsgi/apps-enabled/uwsgi.ini
      notify:
        - restart uwsgi
    - copy: src=deploy/nginx.conf dest=/etc/nginx/nginx.conf
      notify:
        - restart nginx
  handlers:
    - name: restart uwsgi
      service: name=uwsgi state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
